title: Bhaskar Mitra # your name (or website title) here
![Image]("/images/IMG-20200220-WA0020.jpg?raw=true") # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <p style="text-align:left"><a href="https://www.linkedin.com/in/b11genius/" target="_blank">LinkedIn</a></p>
  <p><a href="https://scholar.google.com/citations?user=LKUmrCcAAAAJ&hl=en" target="_blank">Google Scholar</a></p>
  <p><a href="https://www.researchgate.net/profile/Bhaskar_Mitra7" target="_blank">ResearchGate</a></p>
  <p><a href="https://drive.google.com/file/d/0B-zcucFpGDpYSDIySFRoLTVOSVE/view?usp=sharing" target="_blank">CV</a></p>
  
theme: jekyll-theme-minimal
google_analytics: UA-158935836-2 # your Google Analytics tracking ID here
