<p style="text-align:left"><font size="10"> &nbsp<strong> Bhaskar Mitra</strong></font> # your name (or website title) here
![Image]("/images/IMG-20200220-WA0020.jpg?raw=true") # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <p style="text-align:left"><a href="https://www.linkedin.com/in/b11genius/">LinkedIn</a></p>
  <p><a href="https://scholar.google.com/citations?user=LKUmrCcAAAAJ&hl=en" >Google Scholar</a></p>
  <p><a href="https://www.researchgate.net/profile/Bhaskar_Mitra7">ResearchGate</a></p>
  <p><a href="https://drive.google.com/file/d/0B-zcucFpGDpYSDIySFRoLTVOSVE/view?usp=sharing">CV</a></p>
  
theme: jekyll-theme-minimal
google_analytics: UA-158935836-2 # your Google Analytics tracking ID here
