title: Bhaskar Mitra # your name (or website title) here
logo: "/images/IMG-20200220-WA0020.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/b11genius/">LinkedIn</a>
  <a href="https://scholar.google.com/citations?user=LKUmrCcAAAAJ&hl=en">Google Scholar</a>
  <a href="https://www.researchgate.net/profile/Bhaskar_Mitra7">ResearchGate</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-158935836-2 # your Google Analytics tracking ID here
